name: Java Automation

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  java-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: test-automation-java

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Run Tests
        run: mvn clean test

      - name: Generate Allure Report
        if: always()
        run: mvn allure:report

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: test-automation-java/target/site/allure-maven-plugin

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: test-automation-java/target/surefire-reports